import { Voyage } from "./Voyage.model";

export const defaultVoyages: Voyage[] = [
    new Voyage(
        'asia',
        'china',
        'beijing',
        'Beijing now known as Beijing  often marks the logical end of any trip to China. National capital for 800 years, Beijing is now turned to the future, to the control of a rapidly developing China, but is also home to some of the most enigmatic and fabulous sites in the history of ancient China, including the Temple of Sky, Forbidden City and Beijing Summer Palace.Take the time to lose yourself in its old quarters, the hutongs; Fortunately, not all of them were destroyed with the 2008 Beijing Olympics! This China, which for several decades has become somewhat of an endangered species. The effect of the Olympics accentuated the multi-colored modernization of a city where skyscrapers rising higher and higher represent the madness of ambient grandeur. Both modern and traditional, the municipality of Beijing has many sites to visit. Tiananmen Square, the largest square in the world, is home to Mao\'s mausoleum and some museums on Chinese history and the revolution. Fabulous monuments have been classified as Unesco Heritage: the Forbidden City, the Summer Palace and the Temple of Heaven. Each in their own way, they symbolize the frenzy and excessiveness of the emperors of the Ming and Qing dynasties. At the bend of the hutongs, you will discover the Bell and Drum Towers as well as real and authentic China',
        '../../assets/img/japon.png',
        'Juillet'
      ),
      new Voyage(
        'asia',
        'india',
        'new delhi',
        'Delhi is a sprawling city plunged into a thick cloud of pollution and bathed in the incessant sound of horns. A true melting pot, the city is home to 15 million people from the four corners of the Indian subcontinent. Delhi really puts your nerves to the test as soon as you get to its center. Fortunately, there are a few havens of peace there such as Humayun\'s tomb (the pre-Taj Mahal) or Gandhi\'s last resting place, a visit that really touched us. There is a lot to see and do in Delhi, and reasons to love the city. The passage between Old Delhi and New Delhi is very nice. It really feels like a change of world and stepping back in time too. The Humayun tomb of Mughal architecture was built by the widow of the second Mughal emperor. And what a tomb! The materials used are white marble and red sandstone. The site is just splendid. You can visit the interior of the monument and observe the many white marble tombstones.Much of New Delhi, planned by the leading 20th-century British architect Edwin Lutyens, was laid out to be the central administrative area of the city as a testament to Britain\'s imperial ambitions. New Delhi is structured around two central promenades called the Rajpath and the Janpath. The Rajpath, or King\'s Way, stretches from the Rashtrapati Bhavan to the India Gate. The Janpath Hindi: Path of the People, formerly Queen\'s Way, begins at Connaught Circus and cuts the Rajpath at right angles. 19 foreign embassies are located on the nearby Shantipath Hindi: Path of Peace, making it the largest diplomatic enclave in India.At the heart of the city is the magnificent Rashtrapati Bhavan (formerly known as Viceroy\'s House) which sits atop Raisina Hill. The Secretariat, which houses ministries of the government of India, flanks out of the Rashtrapati Bhavan. The Parliament House, designed by Herbert Baker, is located at the Sansad Marg, which runs parallel to the Rajpath. Connaught Place is a large, circular commercial area in New Delhi, modelled after the Royal Crescent in England. Twelve separate roads lead out of the outer ring of Connaught Place, one of them being the Janpath.',
        '../../assets/img/New-Delhi-.jpeg',
        'Juillet'
      ),
      new Voyage(
        'europe',
        'spain',
        'madrid',
        'The cosmopolitan and vibrant capital of Spain, Madrid is an endearing and energetic city that has nothing to envy of its European rivals. Modernism and history are constantly intertwined on every street corner and there is an abundance of small neighborhoods, each prettier than the next. Thanks to its quality of life, its architecture, its cultural offer, its gastronomy and above all its sunny climate all year round, Madrid attracts more and more travelers who come to discover the capital during a weekend or more. stands out for its astonishing cultural and artistic heritage, as evidenced by the Prado and Reina Sofía museums, as well as by its remarkable squares like the Plaza Mayor and by its historic buildings such as the magnificent Palace of Cybele or the Cathedral of the Almudena As you visit, you will discover that Madrid is friendly and lively, especially at nightfall. The Spanish capital has many facets and there is something for everyone. And so you don\'t miss out on anything about this destination, follow our guide to Madrid! During your visit, you will be able to discover the Palacio Real, which is none other than the official residence of the King of Spain, and its sumptuous gardens. You can stroll through the Plaza Mayor surrounded by arcades and porches, locate kilometer zero under the Puerta del Sol or immerse yourself in Spanish bullfighting culture at the Bullring of las Ventas. Whether you are a football fan or not, a visit to the Santiago Bernabéu stadium is a must.',
        '../../assets/img/madrid.webp',
        'Juillet'
      ),
      new Voyage(
        'europe',
        'france',
        'paris',
        'France’s reputation for its cuisine (the French word for ‘kitchen’) precedes it, and whether you seek a cosy neighbourhood bistro or a triple-Michelin-starred temple to gastronomy, you\'ll find that every establishment prides itself on exquisite preparation and presentation of quality produce, invariably served with wine. Enticing patisseries, boulangeries (bakeries), fromageries (cheese shops) and crowded, colourful street markets are perfect for putting together a picnic to take to the city’s beautiful parks and gardens. A host of culinary courses – held anywhere from home kitchens to the world’s most prestigious cookery schools – offers instruction for all schedules, abilities and budgets.The word Parisian is synonymous with style, and fashion shopping is the city’s forte. Paris remains at the forefront of international trends, and browsing emerging and established designer boutiques and flagship haute couture houses is a quintessential part of any visit. You’ll also find hip concept and homewares shops, and resplendent art nouveau department stores, along with a trove of vintage shops and flea markets, atmospheric bookshops and dark-green bouquiniste stalls stocking secondhand titles along the riverbanks, adorable children’s wear and toy shops, art and antique dealers, venerable establishments selling professional cookware, and, of course, gourmet-food and wine shops galore.',
        '../../assets/img/paris.jpeg',
        'Juillet'
      ),
      new Voyage(
        'america',
        'united-states',
        'miami',
        'There is no other city like Miami - it\'s a fact. Nicknamed the “Magic City,” Miami is a unique and exciting blend of hip urban culture, laid-back beachside vibe, and Latin and American traditions. In Miami, you can enjoy the most delicious Latin American cuisine, every night of the week. the week. You will have the chance to taste the best Cuban dishes served outside Havana, the Cuban coffee - to be consumed without moderation - and, of course, the famous Cuban cocktails. You\'ll also experience traditional cuisine from the Caribbean and Latin American countries. Like anything else in this city, a night in Miami is a quintessentially Latin experience - with an American flavor, of course. South Beach in particular is home to some of the world\'s most famous nightclubs and music from top DJs is sure to keep you dancing the night away. Miami is the only city in the United States that can boast of being nestled between two national parks. To the west you\'ll find the Everglades: a swampy expanse of subtropical land, perfect for wilderness adventure. The park\'s many walking and biking trails are ideal places to recover from all the overeating that has happened in Miami.',
        '../../assets/img/miami.jpeg',
        'Juillet'
      ),
      new Voyage(
        'america',
        'united-states',
        'orlondo',
        'Orlando is an active metropolis in central Florida. In people\'s minds, Florida often rhymes with Miami and the Keys. However, the city of Orlando is a constantly expanding metropolis that has nothing to envy of its sister city in the south of the state since it is even the number one tourist destination in Florida. Between amusement parks, museums, restaurants, hotels, animal parks and all the other activities that are offered there all year round, Orlando has become a city where the boredom of the resident and the tourist does not exist. not ! Discover Orlando, the expanding metropolis in central Florida. The climate is humid subtropical. It is therefore essential to consider not only the temperatures (pleasant all year round) but also the degree of humidity. There are no seasons like in Europe. Generally, the hottest and most humid months are from May to October when the barometer can quickly exceed 30 ° and 100% humidity. From October, the humidity drops and the temperature drops to give way to very pleasant weather.',
        '../../assets/img/orlondo.jpeg',
        'Juillet'
      ),
      new Voyage(
        'america',
        'brazil',
        'rio de janeiro',
        'The second largest city in Brazil after Sao Paulo, Rio de Janeiro is a metropolis full of treasures. From Christ the Redeemer to the famous colorful carnival, passing by its legendary beaches, Rio de Janeiro is a destination that makes you dream! Dominating Rio, the Corcovado (the "hunchback" in Portuguese) is a 710-meter-high peak located in the Tijuca Forest, on which stands the statue of Christ the Redeemer. We owe its construction to a French sculptor, Paul Landowski with the participation of a Romanian sculptor, Gheorghe Leonida and the engineer Heitor da Silva. Christ the Redeemer has been listed as a historical monument since 1973 and was voted the 7th New Wonder of the World.Amazing but true, Rio is home to the largest urban forest in the world: the Tijuca Forest which stretches 3,200 hectares and has been declared a World Reserve of the biosphere by Unesco. It is a tropical forest with lush vegetation where you can admire local fauna such as toucans and several species of monkeys. There are several waterfalls (including the largest in Rio: the Cascatinha Taunay) but also several viewpoints over the city such as the Pedra Bonita, the Pedra da Gavea, the Vista Chinesa and the famous Christ the Redeemer. We often confuse Sugar Loaf, "Pão de Açúcar", with Corcovado. The summit rises to 395m in height and is accessible by 2 cable cars, passing by the Morro da Urca. The ride offers a panoramic view of the breathtaking surroundings and from the top one sees the beaches of Leme, Copacabana and Ipanema, as well as the districts of Botafogo and Flamengo. As Sugarloaf Mountain is a staple in Rio, it is also one of the most frequented by visitors.',
        '../../assets/img/bresil.jpeg',
        'Juillet'
      ),
      new Voyage(
        'africa',
        'egypt',
        'cairo',
        'When we think of the Egyptian capital, we immediately think of the Sphinx and the pyramids. But there is much more to discover in Cairo. There is the great Arab souk - where you can buy dozens of gifts while haggling until you lose your breath - the Coptic quarter and its mysteries, the mummies kept in the Cairo museum, the sarcophagus of Tutankhamun, the delta of Nil… There is so much to see in this megalopolis that it is difficult to sum it all up in five steps. Here is what we have to offer. If you really want to experience Cairo, don’t hesitate to climb one of the hills that surround the city. You will be able to see there the citadel of Saladin, defensive bastion and former royal residence. Nothing remains of Saladin\'s palace, but within the citadel you can visit the impressive Alabaster Mosque, so named because this material was used extensively for its construction. This shrine, dominated by a large dome supported by four smaller ones, houses the tomb of the viceroy of Egypt, Mehemet Ali. And of course, we couldn\'t end this article without telling you about the Pyramids and the Great Sphinx, which are the icons of this country. Surrounded by mystery, the pyramids of Cheops, Khafre and Menkaure are a must-see for anyone visiting Cairo. If you are in good physical condition, you can visit the largest of them and walk down the stairs to the burial chamber. But bear in mind that on your return you will have to ride them. This experience may awaken in you a slight feeling of claustrophobia, but a surprise awaits you at the exit of the pyramid: you will feel a sensation of freshness in the middle of the desert!',
        '../../assets/img/egypte.webp',
        'Juillet'
      ),
      new Voyage(
        'africa',
        'morocco',
        'marrakech',
        'Marrakech is very often the first city we visit in Morocco. A key step in a stay in Morocco, visiting the city can take a day for the fastest, a week for those who spend their entire stay there. So what to do in Marrakech In this post entirely devoted to the red city, we will discuss together everything you need to know before visiting Marrakech. What to do, where to stay in the Red City, how to get around or how to get there. Also, we will see the possible activities during a trip here, as well as the excursions from the Red City. Indeed, if you stay a week in Marrakech, you will have plenty of time to make one or two excursions outside the city during your stay. Marrakech, also spelled Marrakesh (مراكش in Arabic), being the most touristic city of Morocco, beyond the monuments and places of interest to visit, there are also many activities. Cooking classes, hammam, day trips outside the red city, the nickname given to the city. There is really something to do in Marrakech ... Walking around the city is not necessarily easy, there are so many things to do that it is essential to make choices when preparing for your trip. what to do in Marrakech without mentioning the medina of the red city. It is certainly even one of the things to prioritize here: walking around the medina with no real purpose. Get lost in the alleys and especially move away from the streets closest to Jemaa el Fna Square. As you move away, you will discover areas of the medina that are much less touristy. Sometimes residential, sometimes with shops for the inhabitants of the medina.',
        '../../assets/img/marrakech.jpeg',
        'Juillet'
      ),
      new Voyage(
        'europe',
        'italy',
        'rome',
        'Rome. Capital of Italy since 1870, it is the site of public administration, but also an important economic and cultural center, with around 2,800,000 inhabitants. The historic center, which brings together the monuments of Ancient Rome and the masterpieces of the Renaissance and Baroque, is one of the largest and most famous in the world. Around the center, then, is a series of neighborhoods (Prati, Testaccio, San Giovanni and Parioli) which were born and developed between the end of the 19th century and the first half of the 20th century. Finally, more on the outskirts, there are residential areas born between the sixties and eighties of the previous century.The city is crossed by a river, the Tiber, which, at the level of the Tiber Island, separates the historic center from the Old district of Trastevere which is today one of the centers of the nightlife of the capital. One of the characteristics of Rome is the presence of large green spaces, even in the city center. At the time, it was the parks of the homes of noble Roman families. It was only in the last century that they became public spaces where one can walk or play sports.To get around Rome, it is possible to use the two metro lines, the various bus lines and the urban railway lines that connect the main stations located along the perimeter of the city.If you arrive in Rome by plane, you can land either at Leonardo da Vinci International Airport in Fiumcino (connected to the city center in about 20 minutes by a train that leaves every 15 minutes) or at Ciampino airport (connected to the city center by dedicated shuttles) .If you choose the train instead, you will arrive at the main station (Roma Termini) which is located in the center and from which it is easy to reach the four corners of the city.',
        '../../assets/img/Rome.jpeg',
        'Juillet'
      )
]